name: Add comment with Netiquette guidelines for PR

on:
  pull_request:
    types:
      - opened
   
jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add a comment to pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_BODY="As a skilled developer, you adhere to the following etiquette guidelines to enhance your contributions: - https://github.wdf.sap.corp/cf-internal-realm/Documentation/blob/master/OpsDevOpsDevOpsDev/live-netiquette.md"
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
               -d "{\"body\": \"$COMMENT_BODY\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"