name: Echo Changed File Names

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      manualTrigger:
        description: 'Manually trigger the workflow'

jobs:
  echo-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo names of changed files
        run: |
          echo "Files changed in this pull request:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
