name: PR HCPCM Validator

on:
  pull_request:
    types:
      - opened

jobs:
  check-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Process files changed in the current commit
        run: |
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            if [ "$file" == "ignore1.txt" ]; then
              echo "Processing file: $file"
              echo "::set-output name=specific-file-changed::true"
            fi
          done

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check for Specific File Changes
        id: check-file-changes
        run: |
          # Specify the path of the file you want to check
          file_to_check="ignore1.txt"

          # Check if the specific file has changed
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          cat changed_files.txt  # Debug: Output the changed files list for inspection

          if grep -q "$file_to_check" changed_files.txt; then
            echo "The file $file_to_check has changed."
            echo "::set-output name=specific-file-changed::true"
          else
            echo "No changes in the file $file_to_check."
            echo "::set-output name=specific-file-changed::false"
          fi

      # ... (rest of your workflow)
