name: Changed files

on:
  pull_request:
    types:
      - opened

jobs:
  check-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Process files changed in the current commit
        run: |
          # Get list of changed files in the PR
          changedFiles=$(git diff --name-only HEAD^)
      
          # Display all changed files for debugging purposes
          echo "Changed files:"
          echo "$changedFiles"
      
          # Check if specific files are changed and set output accordingly
          if echo "$changedFiles" | grep -E 'ignore1.txt|ignore2.txt'; then
            echo "Specific files (ignore1.txt or ignore2.txt) have been changed."
            echo "::set-output name=specific-files-changed::true"
          else
            echo "No changes detected in ignore1.txt or ignore2.txt."
            echo "::set-output name=specific-files-changed::false"
          fi
