name: Hello World Workflow

on:
  push:
    branches:
      - test

  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with API
        run: |
          gh api -X POST \
          http://api.github.com/repo/${ORGANISATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments
          -f body ='
          Commment using API call
          '
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ORGANISATION: ${{github.event.organisation.login}}
          REPOSITORY: ${{github.event.repository.name}}
          ISSUE_NUMBER: ${{github.event.issue.nmuber}}

       
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2.4.0
        with:
          # Message that should be printed in the pull request
          message: "Kindly check the Netiquette document and ensure your PR adhere to that"
          # Path of the file that should be commented
          pr_number: ${{github.event.issue.number}}
   
   
