name: Hello World Workflow

on:
  push:
    branches:
      - test

  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: |
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/sreedhargs89/githubActionPOC/issues/2/comments \
            -f body='Me too other
        shell: bash
        
  commentPR-api:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Pull Request
        # You may pin to the exact commit or the version.
        # uses: thollander/actions-comment-pull-request@dadb7667129e23f12ca3925c90dc5cd7121ab57e
        uses: thollander/actions-comment-pull-request@v2.4.0
        with:
          # Message that should be printed in the pull request
          message: "From PR"
          # Path of the file that should be commented
          pr_number: 2
   
