name: Hello World Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello World - Run"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps: 
      - name: goodbue world
        run: echo "Goodbye world"
        shell: bash
        
