name: Hello World Workflow

on:
  push:
    branches:
      - test

  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: _actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps: 
      - name: goodbue world
        run: echo "Goodbye world"
        shell: bash

  commentPR-api:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with Netquites
        run: | 
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/sreedhargs89/githubActionPOC/issues/2/comments \
            -f body='Me too' 
        
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ORGANIZATION: ${{github.event.organisation.login}}
          REPOSTITORY: ${{github.event.repository.name}}
          ISSUE_NUMBER: ${{github.event.issue.number}}
