name: Hello World Workflow

on:
  push:
    branches:
      - test

  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: |
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/sreedhargs89/githubActionPOC/issues/2/comments \
            -f body='Me too other
        shell: bash
        
  commentPR-api:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with Netquites
        run: | 
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/sreedhargs89/githubActionPOC/issues/2/comments \
            -f body='Me PR |
