name: Hello World Workflow

on:
  push:
    branches:
      - test

  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
         
  commentPR-api:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2.4.0
        with:
          # Message that should be printed in the pull request
          message: "Kindly check the Netiquette document and ensure your PR adhere to that"
          # Path of the file that should be commented
          pr_number: ${{github.event.issue.number}}
   
