name: PR Validation

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title and Description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = github.context.payload.pull_request.title;
            const body = github.context.payload.pull_request.body;
            const issueRegex = /HCPCM-\d+/; // Regex to match the ticket format

            if (!issueRegex.test(title) || !issueRegex.test(body)) {
              const comment = 'This PR title or description doesn\'t contain a valid ticket number. Please edit the PR and add a relevant ticket number.';
              const response = await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              });
            } else {
              const comment = 'Thanks for this PR - Hope you have followed all the guidelines. [Guideline Link]';
              const response = await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              });
            }
