name: PR Validation

on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch: # Manual triggering
    inputs:
      pr_number:
        description: 'Pull Request number'
        required: true

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title and Description
        if: github.event_name != 'workflow_dispatch' # Don't perform checks on manual trigger
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = github.context.payload.pull_request.title;
            const body = github.context.payload.pull_request.body;
            const issueRegex = /HCPCM-\d+/; // Regex to match the ticket format
            
            if (!title || !body) {
              console.log('Missing PR details.');
              process.exit(1);
            }
            
            if (!issueRegex.test(title) || !issueRegex.test(body)) {
              const comment = 'This PR title or description doesn\'t contain a valid ticket number. Please edit the PR and add a relevant ticket number.';
              const response = await github.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              });
            } else {
              const comment = 'Thanks for this PR - Hope you have followed all the guidelines. [Guideline Link]';
              const response = await github.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              });
            }

      - name: Handle PR Title Edits
        if: github.event_name != 'workflow_dispatch' # Don't handle edits on manual trigger
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // The same edit handling script as before

      - name: Manual Trigger Step
        if: github.event_name == 'workflow_dispatch' # Perform checks on manual trigger
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.inputs.pr_number }};
            const comment = 'Manually triggered workflow validation.';
            await github.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
