name: PR Validation

on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch: # Manual triggering
    inputs:
      pr_number:
        description: 'Pull Request number'
        required: true

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title and Description
        if: github.event_name != 'workflow_dispatch' # Don't perform checks on manual trigger
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // The same validation script as before

      - name: Handle PR Title Edits
        if: github.event_name != 'workflow_dispatch' # Don't handle edits on manual trigger
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // The same edit handling script as before

      - name: Manual Trigger Step
        if: github.event_name == 'workflow_dispatch' # Perform checks on manual trigger
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.inputs.pr_number }};
            const comment = 'Manually triggered workflow validation.';
            await github.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
