name: Check Ticket Number
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger the workflow'
        default: 'false'
jobs:
  check-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Extract HCPCM Ticket Number from PR Title or Description
        id: extract-ticket
        run: |
          pattern="HCPCM-[0-9]+"
          title_match=$(grep -oE "$pattern" <<< "${{ github.event.pull_request.title }}")
          description_match=$(grep -oE "$pattern" <<< "${{ github.event.pull_request.body }}")
          if [ -n "$title_match" ]; then
            extracted_ticket="$title_match"
          elif [ -n "$description_match" ]; then
            extracted_ticket="$description_match"
          fi
          echo "::set-output name=extracted-ticket::$extracted_ticket"

      - name: Thank User and Echo Extracted Ticket
        if: steps.extract-ticket.outputs.extracted-ticket
        run: |
          echo "Thank you for mentioning HCPCM ticket ${{ steps.extract-ticket.outputs.extracted-ticket }}!"
      
      - name: Add Comment if Ticket is Missing
        if: steps.check-description.outputs.ticket-missing == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_BODY="Please include a valid HCPCM ticket number in the PR description."
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"$COMMENT_BODY\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
