name: Check Ticket Number
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger the workflow'
        default: 'false'
jobs:
  check-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Description
        id: check-description
        run: |
          echo "PR Description: '${{ github.event.pull_request.body }}'"
          pattern="HCPCM-[0-9]+"
          echo "Pattern: $pattern"
          if ! grep -qE "$pattern" <<< "${{ github.event.pull_request.body }}"; then
            echo "Pattern not found!"
            echo "::set-output name=ticket-missing::true"
          else
            echo "Pattern found!"
          fi

      - name: Add Comment if Ticket is Missing
        if: steps.check-description.outputs.ticket-missing == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_BODY="Please include a valid HCPCM ticket number in the PR description."
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"$COMMENT_BODY\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
